export const TYPES = {
  LOAD_CART_FROM_STORAGE: "LOAD_CART_FROM_STORAGE", // <-- Nueva acción
  READ_STATE: "READ_STATE",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ONE_ITEM: "REMOVE_ONE_ITEM",
  REMOVE_ALL_ITEMS: "REMOVE_ALL_ITEMS",
  CLEAR_CART: "CLEAR_CART",
};